# Generated by Django 2.1.5 on 2019-01-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome do cliente')),
                ('idade', models.IntegerField(max_length=100, verbose_name='idade')),
                ('sexo', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')], default='')),
                ('formacao', models.CharField(max_length=100, verbose_name='Formação')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
